language: java
jdk:
  - oraclejdk7
  - openjdk7
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install apt-transport-https
  - sudo sh -c 'echo "deb https://sdkrepo.atlassian.com/debian/ stable contrib" >> /etc/apt/sources.list'
  - sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys B07804338C015B73
  - sudo apt-get update -qq
  - sudo apt-get install apt-transport-https
  - sudo apt-get install atlassian-plugin-sdk
install: atlas-mvn install -DskipTest=true
script: atlas-unit-test